global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192:168.1.30:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['192.168.1.30:9100']  # бо network_mode: host

  - job_name: 'app'
    static_configs:
      - targets: ['app:80']  # перевір, чи твоя апка має /metrics

  # якщо хочеш додати redis_exporter або postgres_exporter пізніше
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis_exporter:9121']
  #
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres_exporter:9187']

