apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}

    http {
      server {
        listen 80;
        server_name _;

        location /dashboard/ {
          proxy_pass http://dashboard.kube/;
          proxy_set_header Host $host;
        }
      }
    }

