apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_DB: nextcloud
  POSTGRES_USER: usr
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-config
data:
  POSTGRES_HOST: postgres-service
  POSTGRES_DB: nextcloud
  POSTGRES_USER: usr
  REDIS_HOST: redis-service
  NEXTCLOUD_ADMIN_USER: admin
  NEXTCLOUD_TRUSTED_DOMAINS: localhost nextcloud.local 127.0.0.1 nginx-proxy-service 10.244.0.1 192.168.1.160 192.168.49.2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: 'kubernetes-pods'
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true

