{
 "title": "Pods errors",
 "tags": [ "monitoring" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "datasource", "label": "DataSource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "OOM killed pods for selected interval",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "OOM killed pods",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pod, namespace) (kube_pod_container_status_last_terminated_reason{reason=\"OOMKilled\",namespace=~\"$namespace\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error exit pods for selected interval",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }
  },
  {
   "title": "Error exit codes",
   "type": "stat",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pod, namespace) (kube_pod_container_status_last_terminated_reason{reason=\"Error\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Pod restarts for selected interval",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }
  },
  {
   "title": "Top 10 restarting pods",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, \n  sum by (pod, namespace) (\n    kube_pod_container_status_restarts_total{namespace=~\"$namespace\"}\n  )\n)"
    }
   ]
  },
  {
   "title": "funny circle of exitcodes for pods",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod, namespace, reason) (\n  kube_pod_container_status_last_terminated_reason{namespace=~\"$namespace\"}\n)"
    }
   ]
  }
 ]
}