apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anythingllm-pvc
  namespace: open-webui
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path  # або твій StorageClass, якщо інший

